services:
  pivotal:
    build:
      context: .
      dockerfile: Dockerfile
    image: huffmanks/pivotal:${RELEASE_VERSION:-latest}
    container_name: pivotal
    ports:
      - "${PORT:-3011}:${PORT:-3011}"
    environment:
      PORT: ${PORT:-3011}
    restart: unless-stopped
